# 演習問題1
2つのサイコロX,Yを同時に1回振って、出た目をそれぞれ(x,y)とおき、z=x+yとおく。このとき、z=2, 3, ..., 12となる場合の数を求めよ。

In [0]:
from collections import defaultdict
import itertools
import numpy as np

## 全探索で解く

In [16]:
ans = defaultdict(int)

for x,y in itertools.product(range(1,7), repeat=2):
  z = x + y
  ans[z] += 1

ans

defaultdict(int,
            {2: 1,
             3: 2,
             4: 3,
             5: 4,
             6: 5,
             7: 6,
             8: 5,
             9: 4,
             10: 3,
             11: 2,
             12: 1})

In [17]:
print('z', 'ans')
for z in range(2,13):
  print(z, ans[z])

z ans
2 1
3 2
4 3
5 4
6 5
7 6
8 5
9 4
10 3
11 2
12 1


## numpyで解く


In [40]:
# https://note.nkmk.me/python-numpy-arange-linspace/
x = np.arange(1,7)
y = np.arange(1,7)

# https://python.atelierkobato.com/meshgrid/
X,Y = np.meshgrid(x, y)
Z = X + Y

Z

array([[ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10, 11],
       [ 7,  8,  9, 10, 11, 12]])

In [42]:
# https://note.nkmk.me/python-numpy-unique/

z, counts = np.unique(Z, return_counts=True)
print(z)
print(counts)

[ 2  3  4  5  6  7  8  9 10 11 12]
[1 2 3 4 5 6 5 4 3 2 1]
